/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PocRouteImport } from './routes/poc'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PocIndexRouteImport } from './routes/poc.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PocBurgigRouteImport } from './routes/poc.burgig'
import { Route as BlogNewsIdRouteImport } from './routes/blog.news.$id'
import { Route as BlogArticlesIdRouteImport } from './routes/blog.articles.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PocRoute = PocRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PocIndexRoute = PocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PocRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const PocBurgigRoute = PocBurgigRouteImport.update({
  id: '/burgig',
  path: '/burgig',
  getParentRoute: () => PocRoute,
} as any)
const BlogNewsIdRoute = BlogNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => BlogRoute,
} as any)
const BlogArticlesIdRoute = BlogArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/poc': typeof PocRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/poc/burgig': typeof PocBurgigRoute
  '/blog/': typeof BlogIndexRoute
  '/poc/': typeof PocIndexRoute
  '/blog/articles/$id': typeof BlogArticlesIdRoute
  '/blog/news/$id': typeof BlogNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/poc/burgig': typeof PocBurgigRoute
  '/blog': typeof BlogIndexRoute
  '/poc': typeof PocIndexRoute
  '/blog/articles/$id': typeof BlogArticlesIdRoute
  '/blog/news/$id': typeof BlogNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/poc': typeof PocRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/poc/burgig': typeof PocBurgigRoute
  '/blog/': typeof BlogIndexRoute
  '/poc/': typeof PocIndexRoute
  '/blog/articles/$id': typeof BlogArticlesIdRoute
  '/blog/news/$id': typeof BlogNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/impact'
    | '/poc'
    | '/projects'
    | '/sitemap.xml'
    | '/support'
    | '/poc/burgig'
    | '/blog/'
    | '/poc/'
    | '/blog/articles/$id'
    | '/blog/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/impact'
    | '/projects'
    | '/sitemap.xml'
    | '/support'
    | '/poc/burgig'
    | '/blog'
    | '/poc'
    | '/blog/articles/$id'
    | '/blog/news/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/impact'
    | '/poc'
    | '/projects'
    | '/sitemap.xml'
    | '/support'
    | '/poc/burgig'
    | '/blog/'
    | '/poc/'
    | '/blog/articles/$id'
    | '/blog/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GovernanceRoute: typeof GovernanceRoute
  ImpactRoute: typeof ImpactRoute
  PocRoute: typeof PocRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc': {
      id: '/poc'
      path: '/poc'
      fullPath: '/poc'
      preLoaderRoute: typeof PocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poc/': {
      id: '/poc/'
      path: '/'
      fullPath: '/poc/'
      preLoaderRoute: typeof PocIndexRouteImport
      parentRoute: typeof PocRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/poc/burgig': {
      id: '/poc/burgig'
      path: '/burgig'
      fullPath: '/poc/burgig'
      preLoaderRoute: typeof PocBurgigRouteImport
      parentRoute: typeof PocRoute
    }
    '/blog/news/$id': {
      id: '/blog/news/$id'
      path: '/news/$id'
      fullPath: '/blog/news/$id'
      preLoaderRoute: typeof BlogNewsIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/articles/$id': {
      id: '/blog/articles/$id'
      path: '/articles/$id'
      fullPath: '/blog/articles/$id'
      preLoaderRoute: typeof BlogArticlesIdRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogArticlesIdRoute: typeof BlogArticlesIdRoute
  BlogNewsIdRoute: typeof BlogNewsIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogArticlesIdRoute: BlogArticlesIdRoute,
  BlogNewsIdRoute: BlogNewsIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PocRouteChildren {
  PocBurgigRoute: typeof PocBurgigRoute
  PocIndexRoute: typeof PocIndexRoute
}

const PocRouteChildren: PocRouteChildren = {
  PocBurgigRoute: PocBurgigRoute,
  PocIndexRoute: PocIndexRoute,
}

const PocRouteWithChildren = PocRoute._addFileChildren(PocRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GovernanceRoute: GovernanceRoute,
  ImpactRoute: ImpactRoute,
  PocRoute: PocRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
